### PR TITLE
Added target page

### PR DESCRIPTION
**Pull request by kflores772**

### CODE REVIEW

**Comment by kflores772** [comment]
Please do not merge yet

**Comment by kflores772** [comment]
https://github.com/blackberry/webworks-gui/issues/11

@bryanhiggins r?
@rcruz r?

**Comment by bryanhiggins** [comment]
This looks good.

Minor issues: 
- Only name and IP should be required fields.
- Change "build target" to "install target"

**Comment by kflores772** [comment]
@bryanhiggins changes have been made to reflect those minor issues.

**Comment by bryanhiggins** [comment]
Merged

**Pull request closed without merging**
