### PR TITLE
Titlebar adjustments with smaller screen

### PR DESCRIPTION
**Pull request by rcruz**

### CODE REVIEW

**Comment by rcruz** [comment]
New appearance: 
screen shot 2014-04-22 at 11 43 13 am

Thoughts?

**Comment by rcruz** [comment]
@bryanhiggins r?

**Comment by bryanhiggins** [comment]
Hide the hippo completely? @kwallis ?

**Comment by rcruz** [comment]
Hippo image removed for smaller screens.

**Pull request closed without merging**
