### PR TITLE
Change implementation of Build and Install from "webworks run" to the tw...

### PR DESCRIPTION
**Pull request by rcruz**
...o stage build and deploy

### CODE REVIEW

**Comment by rcruz** [comment]
Closes https://github.com/blackberry/webworks-gui/issues/26

**Comment by bryanhiggins** [comment]
Cordova-CLI recently added --release to the run command.

I'll update cordova-blackberry and then the GUI can go back to running a single command.

**Comment by bryanhiggins** [comment]
Good to go: https://github.com/blackberry/cordova-blackberry/commit/34fbc8f2c9999bc7eca4571cbc23661e8c85f6ce

**Comment by jamesjhedley** [comment]
FYI, testing this.

**Comment by jamesjhedley** [comment]
r+

**Comment by jamesjhedley** [comment]
I seem to be running into the below error when attempting to "build and install" with debug mode selected.
`
  error: unknown option --debug
`

**Comment by rcruz** [comment]
Updated. Please retest

**Comment by jamesjhedley** [comment]
Verified. `Build` and `Build and Install` options work as expected for debug and release builds.
Please merge.

**Pull request closed without merging**
